
# Copyright 2025 Apoorv Parle
# SPDX-License-Identifier: Apache-2.0

FROM ubuntu:24.04

RUN apt-get update && \
    apt-get install -y python3 python3-dev python3-venv python3-pip gcc build-essential cython3 patchelf

RUN python3 -m pip install SystemdUnitParser --break-system-packages

WORKDIR /build

